export const sample_designs: any[] = [
  {
    id: "1",
    name: "Wooden Twist Rafuf Wooden Intersecting Wall Shelves",
    price: 1490,
    manufacturer: "Shiraz Handicrafts",
    stars: 4.2,
    imageUrl: "assets/design1.jpg",
    tags: ["Wall Mount", "Wall decor", "Living Room"],
  },
  {
    id: "2",
    name: "Bikri Kendra - Hexagon 20 Golden mirror stickers for wall",
    price: 219,
    manufacturer: "	shreeji venalicium solution",
    stars: 4.3,
    imageUrl: "assets/design2.jpg",
    tags: ["Living Room", "Glass Decor", "Mirror Design"],
  },
  {
    id: "3",
    name: "Hanging Bells Wind Chimes Showpiece",
    price: 189,
    manufacturer: "Intellozene",
    stars: 4.1,
    imageUrl: "assets/design3.jpg",
    tags: ["Home Decor", "Pooja Room"],
  },
  {
    id: "4",
    name: "Fluffy Pampas Grass Set of 4 Artificial Flowers for Vase ",
    price: 549,
    manufacturer: "TIED RIBBONS",
    stars: 3.8,
    imageUrl: "assets/design4.jpg",
    tags: ["Home Decor", "Party", "Living Room"],
  },
  {
    id: "5",
    name: "Shoper cart Wooden Wall Shelve For Home Decoration Items,Showcase",
    price: 799,
    manufacturer: "walia traderss",
    stars: 3.5,
    imageUrl: "assets/design5.jpg",
    tags: ["Wall decor", "Living Room"],
  },
  {
    id: "6",
    name: "Wooden Wall Mounted TV Unit, Cabinet with TV Stand Unit Wall Shelf for Living Room",
    price: 2042,
    manufacturer: "Shiraz Handicrafts",
    stars: 4.5,
    imageUrl: "assets/design6.jpg",
    tags: ["Wall Mount", "TV Stand", "Living Room"],
  },
];

export const sample_tags: any[] = [
  { name: "All", count: 6 },
  { name: "Wall Mount", count: 2 },
  { name: "TV Stand", count: 1 },
  { name: "Living Room", count: 5 },
  { name: "Wall decor", count: 2 },
  { name: "Pooja Room", count: 1 },
  { name: "Glass Decor", count: 1 },
  { name: "Home Decor", count: 2 },
  { name: "Mirror Design", count: 1 },
];

export const sample_users: any[] = [
  {
    name: "Shrinithi",
    email: "shri@gmail.com",
    password: "shri@123",
    address: "Tirunelveli",
    isAdmin: true,
  },
  {
    name: "Kaavya",
    email: "kaavya@gmail.com",
    password: "kaavya@123",
    address: "Madurai",
    isAdmin: false,
  },
  {
    name: "Krish",
    email: "krish@gmail.com",
    password: "krish@123",
    address: "Chennai",
    isAdmin: false,
  },
  {
    name: "Ajay",
    email: "ajay@gmail.com",
    password: "ajay@123",
    address: "Tuticorin",
    isAdmin: false,
  },
];
